instances:
  - name: uniproxy-01
    replicas: 2
    nodePort: 30080
    connections:
      - name: uniproxy-02
        type: http
        host: uniproxy-02.dephealth-uniproxy.svc
        port: "8080"
        path: "/"
      - name: uniproxy-03
        type: http
        host: uniproxy-03.dephealth-uniproxy.svc
        port: "8080"
        path: "/"

  - name: uniproxy-02
    replicas: 2
    connections:
      - name: redis
        type: redis
        host: redis.dephealth-redis.svc
        port: "6379"
      - name: grpc-stub
        type: grpc
        host: grpc-stub.dephealth-grpc-stub.svc
        port: "9090"
      - name: uniproxy-04
        type: http
        host: uniproxy-04.dephealth-uniproxy-2.svc
        port: "8080"
        path: "/"

  - name: uniproxy-03
    replicas: 3
    connections:
      - name: postgresql
        type: postgres
        host: postgresql.dephealth-postgresql.svc
        port: "5432"
        database: dephealth
        username: dephealth
        password: dephealth-test-pass
