apiVersion: v1
kind: ConfigMap
metadata:
  name: dephealth-ui-config
  namespace: {{ include "dephealth-ui.namespace" . }}
  labels:
    {{- include "dephealth-ui.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
