{{- range .Values.instances }}
{{- if .nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-nodeport
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "dephealth-uniproxy.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ .name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: dephealth
  ports:
    - port: 8080
      targetPort: http
      nodePort: {{ .nodePort }}
      name: http
{{- end }}
{{- end }}
