apiVersion: v2
name: dephealth-ui
description: Визуализация топологии и здоровья микросервисов (dephealth-ui)
version: 0.5.1
appVersion: "0.11.4"
type: application
keywords:
  - dephealth
  - topology
  - visualization
  - monitoring
