apiVersion: v2
name: dephealth-ui
description: Визуализация топологии и здоровья микросервисов (dephealth-ui)
version: 0.8.0
appVersion: "0.15.0"
type: application
keywords:
  - dephealth
  - topology
  - visualization
  - monitoring
