apiVersion: v2
name: dephealth-ui
description: Визуализация топологии и здоровья микросервисов (dephealth-ui)
version: 0.9.0
appVersion: "0.16.0"
type: application
keywords:
  - dephealth
  - topology
  - visualization
  - monitoring
