apiVersion: v2
name: dephealth-ui
description: Визуализация топологии и здоровья микросервисов (dephealth-ui)
version: 0.5.0
appVersion: "0.10.13"
type: application
keywords:
  - dephealth
  - topology
  - visualization
  - monitoring
