# dephealth-ui â€” homelab overrides

global:
  pushRegistry: "harbor.kryukov.lan/library"
  namespace: dephealth-ui
  gateway:
    name: eg
    namespace: envoy-gateway-system

image:
  name: dephealth-ui
  tag: v0.14.2-5
  pullPolicy: Always

route:
  enabled: true
  hostname: dephealth.kryukov.lan

tls:
  enabled: false

customCA:
  enabled: true
  configMapName: custom-ca
  key: ca.crt

config:
  server:
    listen: ":8080"
  topology:
    lookback: "1h"  
  datasources:
    prometheus:
      url: "http://victoriametrics.dephealth-monitoring.svc:8428"
    alertmanager:
      url: "http://alertmanager.dephealth-monitoring.svc:9093"
  cache:
    ttl: 15s
  auth:
    type: "none"
  grafana:
    baseUrl: "http://grafana.kryukov.lan"
    dashboards:
      cascadeOverview: "dephealth-cascade-overview"
      rootCause: "dephealth-root-cause"
      serviceStatus: "dephealth-service-status"
      linkStatus: "dephealth-link-status"
      serviceList: "dephealth-service-list"
      servicesStatus: "dephealth-services-status"
      linksStatus: "dephealth-links-status"
