# dephealth-ui â€” homelab overrides

global:
  pushRegistry: "harbor.kryukov.lan/library"
  namespace: dephealth-ui
  gateway:
    name: eg
    namespace: envoy-gateway-system

image:
  name: dephealth-ui
  tag: v0.5.0
  pullPolicy: Always

route:
  enabled: true
  hostname: dephealth.kryukov.lan

tls:
  enabled: false

customCA:
  enabled: true
  configMapName: custom-ca
  key: ca.crt

config:
  server:
    listen: ":8080"
  datasources:
    prometheus:
      url: "http://victoriametrics.dephealth-monitoring.svc:8428"
    alertmanager:
      url: "http://alertmanager.dephealth-monitoring.svc:9093"
  cache:
    ttl: 15s
  auth:
    type: "oidc"
    oidc:
      issuer: "https://dex.kryukov.lan"
      clientId: "dephealth-ui"
      clientSecret: "ZGVwaGVhbHRoLXVpLXNlY3JldA"
      redirectUrl: "https://dephealth.kryukov.lan/auth/callback"
  grafana:
    baseUrl: ""
    dashboards:
      serviceStatus: "dephealth-service-status"
      linkStatus: "dephealth-link-status"
