# Переопределения для домашнего окружения (harbor.kryukov.lan)
global:
  imageRegistry: harbor.kryukov.lan/docker
  storageClass: nfs-client

grafana:
  rootUrl: "http://grafana.kryukov.lan"
  route:
    enabled: true
    hostname: grafana.kryukov.lan
    gateway:
      name: eg
      namespace: envoy-gateway-system

